### ISSUE TITLE
New example requested

### ISSUE THREAD

**Issue by AntaresR** [uias/Tabman-Styles#2]
# Style Request
Hello! It is an awesome library but I am kinda of a newbie on Swift.
## Description
 I was wandering if you could do a custom example of blockTabBar with white letters and different color background? I am not sure how to do it.

## Images
![colores app-03](https://user-images.githubusercontent.com/8839805/33464961-33e9c36a-d613-11e7-8d4a-044b10aadbe8.png)

## Useful links
Thanks!

**Comment by msaps** [comment]
@AntaresR Hey! This appearance config should give you what you want:

```swift
bar.style = .blockTabBar
bar.appearance = TabmanBar.Appearance({ (appearance) in
      appearance.style.background = .solid(color: .purple)
      appearance.indicator.color = .red
      appearance.state.color = .white
      appearance.state.selectedColor = .white
})
```
