### ISSUE TITLE
Changing Tabman background color

### ISSUE THREAD

**Issue by Ahyox** [uias/Tabman-Styles#4]
# Style Request

## Description
ℹThanks for the open source library, it's a life saver. I'm trying to change Tabman background from the default grey color to green and the selector from blue to white but can't seems to know how to do that. Please check the attached image. I await your response. Thanks

## Images
ℹ 
![simulator screen shot - iphone 8 plus - 2018-07-26 at 23 43 07](https://user-images.githubusercontent.com/7904501/43292553-be662ac6-912d-11e8-916f-d1b16f45b373.png)

## Useful links
ℹ Please replace this with any useful links that you think will help to implement the style.

**Comment by msaps** [comment]
@Ahyox please check out the [Appearance](
https://github.com/uias/Tabman#appearance) docs in the README - also a full list of properties is [available](https://github.com/uias/Tabman/blob/master/Docs/APPEARANCE.md).

**Comment by msaps** [comment]
@Ahyox just a note for future issues, probably better to put them in the main uias/Tabman repo 😄
